# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
    - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
        registry-url: https://registry.npmjs.org/
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install latest NPM
      run: npm install -g npm@latest

    - run: bun test

    - run: npm run build && npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
